### ISSUE TITLE
Outreach to three community groups

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#10]
Outreach that mixes traditional community awareness raising and social mapping with comunity-driven technology developent with online team
- [ ] Prepare documented research questions and methodologies for Q3 SC related workshops and collaborations. (community problem definition; from grant deliverables)

**Comment by steviepubliclab** [comment]
Need a meeting with jywarren (+Shannon?) to identify what we are looking for in community groups. (ideas on groups, locations, focus on specific issues?)  

Google Doc: https://docs.google.com/document/d/16tHQFsFo4WgzmHXaUhKRj3yg8LfP86KCwMCz3hSKnv8/edit?usp=sharing

**Comment by jywarren** [comment]
@steviepubliclab noting that we want to wait on this for the "beta" kit relaunch #21

**Comment by steviepubliclab** [comment]
Adding #6 (Outreach that mixes traditional community awareness raising and social mapping with comunity-driven technology developent with online team)

**Comment by steviepubliclab** [comment]
Interested in inviting a community group to do a session on this with us at the BR?

**Comment by jywarren** [comment]
sounds cool -- esp with the workshop format coming together, running a
workshop is less of an unknown now, right?

**Comment by steviepubliclab** [comment]
Added a group to the Outreach Communications Doc (https://docs.google.com/document/d/16tHQFsFo4WgzmHXaUhKRj3yg8LfP86KCwMCz3hSKnv8/edit). they are in Houma, so could maybe come to a session at the BR

**Comment by steviepubliclab** [comment]
4 potential community groups identified. email communication with all.

**Comment by steviepubliclab** [comment]
Writing an MOU for work with GRN. It will include:
- Providing feedback on the OTK.
- Assisting developing of sample protocols and weighing in on field sample collection and preparation.
- Assist in highlighting community use-cases for the tool (will monitor the NRC reports for oil contaminants and loop in on issues when the kit could be useful). 
- Partner on local community trainings (including a joint one on OTK and filing NRC reports)
