### ISSUE TITLE
monthly workshops and trainings

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#11]
**Mar 2015-Feb 2016 -- re-assign to later milestones as we progress** on spectroscopy and field sampling techniques. Does this mean in person? (stevie, w/ jeff & mathew)

**Comment by steviepubliclab** [comment]
I think this was for people to get involved with the technology (develop, teach it, use it).

**Comment by steviepubliclab** [comment]
We need to identify how to make these consistent. Also, when do are the monthly trainings supposed to start?

**Comment by jywarren** [comment]
I think we should build on the workshop this week and make a plan based on what we learn, and sync with the Kickstarter. The schedule's getting rearranged due to the Infragrams but it'll be fine -- we're making lots of progress on other kinds of documentation, etc!

**Comment by steviepubliclab** [comment]
Ok from what I understand, this should be starting up around March, if I'm looking at the grant correctly. I was wondering if all these meet-ups have to be based around the OTK? I've also started a monthly water quality meetup (these are going at least through June), and we do bi-monthly mapping events as well. Just wondering if I can cross over at all?

**Comment by jywarren** [comment]
I believe so; double check w/ becki though.

**Comment by steviepubliclab** [comment]
Here is where I've been tracking these, it includes other grants as well. I missed one in Aug. for homebrew, which I mentioned to Shannon then, but there are a lot of repeats in other months. https://docs.google.com/spreadsheets/d/1HfiyhwwdQemq9__QhBsX0pJldGp3uHfzCAvW8Q2Y-U4/edit#gid=0
