### ISSUE TITLE
Quarterly barnraising

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#12]
**Mar 2015-Feb 2016**

**Comment by ebarry** [comment]
barnraisings that go for multiple days or single-day "toolshed raisings" ?

**Comment by jywarren** [comment]
:-P no idea, it was just copied over from the original plan, which predated
most of these new types of events

**Comment by steviepubliclab** [comment]
I think the 2 this year are good for now, but we can open the idea up for more in the future.

**Comment by steviepubliclab** [comment]
Spring Fling!: http://publiclab.org/notes/stevie/02-03-2015/gulf-coast-spring-fling
June in Chicago,
Late summer in Houma??? (TBD)
Big BR at LUMCON
