### ISSUE TITLE
develop basic tests for specific contaminants

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#14]
**Dec 2015-Feb 2016:** for smartphone and desktop

**Comment by steviepubliclab** [comment]
Communications on Alpha Test kits: http://docs.google.com/document/d/1a6wVdkfp-P0lGlEUHNMcBdDql2Ld0fifX-Kxqpcrq-I/edit

**Comment by jywarren** [comment]
To what degree does this overlap with #7? Could we merge? Alternatively, could we use this for our documentation task, as discussed today, where we develop a focused guide for the Oil Testing Kit with stages something like **Collect, Scan, Compare**?
