### ISSUE TITLE
Chemical Corridor Cookbook

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#15]
Listing contaminants; where are we now with these? Relate to http://publiclab.org/wiki/common-water-contaminants

Community toolkit will be in testing by fall 2015, #13 and may include this

**Comment by jywarren** [comment]
@mathewlippincott  points out that this is a convergence of lots of our projects; may push towards end of grant period

**Comment by mathewlippincott** [comment]
Fall 2015

**Comment by jywarren** [comment]
Potentially OTK pocket/field guide

**Comment by jywarren** [comment]
http://publiclab.org/wiki/chemical-corridor-cookbook will be the table of contents

Dec/Jan - after @ebarry does tool page standardization

Advocacy, PM, blablabla, chapters on each program area.

Point Maria to this as an outline

**Comment by jywarren** [comment]
merged into #13
