### ISSUE TITLE
Outreach to 3 community groups

### ISSUE THREAD

**Issue by steviepubliclab** [publiclab/homebrew-sensing#18]
Solidify partnerships with three core community groups in the Gulf Coast region to partner with throughout the duration of this project (focus on support where digital access is minimal)

**Comment by jywarren** [comment]
If you could leave a comment indicating how the issue was resolved that'd be great! Thanks! And if you merge it into another you can cite it by writing (for example) #18 and it should auto link.

**Comment by steviepubliclab** [comment]
looks like i can't comment on it if its closed. Sorry! I didn't realize I
could rename them. Figured that out now.

**Comment by jywarren** [comment]
Oh, but can you reopen it? Hmm, I should also give you more permissions if
that's true.

**Comment by steviepubliclab** [comment]
Closed #10

**Comment by jywarren** [comment]
ah, ok, you moved this to #10. gotcha tnx
