### ISSUE TITLE
Evaluation plan

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#20]
We have some planning in place on this and are waiting for a photo of it to be posted. More soon.

**Comment by jywarren** [comment]
Hi, @steviepubliclab - could you check with Shannon about this? thanks!

**Comment by sdosemagen** [comment]
Forwarding photo

On Mon, Jun 9, 2014 at 2:46 PM, Jeffrey Warren notifications@github.com
wrote:

> Hi, @steviepubliclab https://github.com/steviepubliclab - could you
> check with Shannon about this? thanks!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/publiclab/homebrew-sensing/issues/20#issuecomment-45535116
> .

## 

@sdosemagen

**Comment by jywarren** [comment]
Let's chat about this during the NOLA visit!

**Comment by jywarren** [comment]
shannon sez we'll do something with analytics towards end of grant. +1
