### ISSUE TITLE
Develop clear, focused, visual docs for current state of Oil Testing Kit

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#22]
Collect, Scan, Compare?

at http://publiclab.org/wiki/oil-testing-kit

**Comment by jywarren** [comment]
I spent some time today on the "Collect" section @steviepubliclab @mathewlippincott -- next up, scanning it, then comparing to known samples: http://publiclab.org/wiki/oil-testing-kit

**Comment by jywarren** [comment]
Really coming along, also highlighting holes in the process under http://publiclab.org/wiki/oil-testing-kit#Challenges

still needs better and more illustrations, and the middle section has lots of room for improvement as we refine the kit more.

**Comment by jywarren** [comment]
Also looking to redevelop the Spectrometer wiki page; getting there; input?

![spectrometer-wiki-page](https://cloud.githubusercontent.com/assets/24359/3692415/54641bd6-135c-11e4-93c2-1c16fa5d5110.png)

**Comment by jywarren** [comment]
OK done minus the lead image: http://publiclab.org/wiki/spectrometer

**Comment by steviepubliclab** [comment]
I liked the first image. These are great.

**Comment by jywarren** [comment]
we'll post the real lead image soon (as in this mockup), but i'm still
trying to figure out what's going on with the lead image bug on the
website, so sorry for the delay.
