### ISSUE TITLE
make docs more accessible

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#24]
- [x] Touchup/collect photos
- [x] separate about `kit/program` vs `how to` vs `history`
- [x] Add sections for:
  - [x] status
  - [x] fellowships
  - [x] limitations
  - [x] collect, scan, compare
- [x] revise http://publiclab.org/wiki/spectrometer#Make+a+spectrometer
- [x] revise http://publiclab.org/wiki/desktop-spectrometry-kit-3-0
- [x] make collapsible sections!
- [x] pick up again here: http://publiclab.org/wiki/oil-testing-kit#Illuminate+the+sample
  - [x] add annotations to the "perpendicular" image
- [x] post Google Form for beta signups

**Comment by steviepubliclab** [comment]
http://publiclab.org/notes/stevie/08-13-2014/working-oil-testing-event-guide

**Comment by jywarren** [comment]
Rad. We should at some point port that to a wiki page so others can
collaborate (say, if Benjamin or Liz want to add input, revisions) and
interlink it with the Oil Testing Kit wiki page.

**Comment by jywarren** [comment]
I'll be helping with this over the next couple weeks in coord with @mathewlippincott
