### ISSUE TITLE
verify oil contamination of different media

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/homebrew-sensing#25]
can we compare fluorescence spectra when oil is contaminating different media?
oil in sand, soil, plant matter, and water?
old oil vs new oil from the same sample?

**Comment by jywarren** [comment]
homebrew fellowship being written around aqueous oil: http://publiclab.org/notes/mathew/04-07-2015/can-a-surface-sheen-be-collected-for-oil-testing

:-)

Fellowships at #28, and if that is easy, move on to soil, etc.

**Comment by jywarren** [comment]
Matej now working on this!
