### ISSUE TITLE
community partnerships

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#3]
**Mar-May 2014:** GC outreach role begins. Solidify partnerships with three core community groups in the Gulf Coast region to partner with throughout the duration of this project (focus on support where digital access is minimal)

**Comment by steviepubliclab** [comment]
If I add this on to the other outreach one can we close it? seems a little redundant

**Comment by jywarren** [comment]
Yep!

**Comment by steviepubliclab** [comment]
closed #6
