### ISSUE TITLE
develop workshop formats

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#5]
**Mar-May 2014:** Stevie + Jeff - Development and conceptualization of workshops structure (replicable)

**Comment by steviepubliclab** [comment]
Perhaps we can talk about this at the NE Barnraising

**Comment by jywarren** [comment]
perhaps base on http://publiclab.org/wiki/makezine

**Comment by jywarren** [comment]
Perhaps use already completed desktop spectrometers (which people can take apart or look inside of) but make the "meat" of the event around sample collection & prep & analysis, a la http://publiclab.org/wiki/oil-testing-kit#NE+Barnraising+brainstorm

**Comment by steviepubliclab** [comment]
Page to conceptualize event: https://docs.google.com/document/d/1qTf7E5MZCbPs2kOhgZd8a-M_jvdho6IQNX2REAe1GPY/edit

**Comment by jywarren** [comment]
@steviepubliclab posted an event here: http://publiclab.org/notes/stevie/07-09-2014/a-new-orleans-event-samples-with-spectrometry

**Comment by jywarren** [comment]
Let's start to think about posting event guides based on what we've learned?

**Comment by jywarren** [comment]
@steviepubliclab - in communication with @ebarry and Benjamin, is there interest, or are we kind of ready to develop a wiki page guide for the kind of workshop we ran? Someone from CivicLab already posted an activity guide for balloon mapping so that's promising.

**Comment by steviepubliclab** [comment]
http://publiclab.org/notes/stevie/08-13-2014/working-oil-testing-event-guide Working guide page, 

Also Benjamin will host 2 sessions on this, a small one in September, and a bigger one in October, we should use these to refine our processes.

**Comment by ebarry** [comment]
Also, NYC is planning to run this workshop in the first week of November for the International Crisis Mappers Conference. We will be excited to use your event guide and see how people iterate on it in upcoming sessions!

**Comment by steviepubliclab** [comment]
Great! I would love to get comments and feedback on it as the kit develops
and we refine the workshop to suit developments. Thanks!

**Comment by jywarren** [comment]
"Timeline" style workshops prototyped at Propeller and tested in NYC and Chicago.

**Comment by steviepubliclab** [comment]
New Workshop to be written with the new kit: focus on interest from specific groups
- use in the field
- adding to research (false positives, tallying/sampling for regional contaminants, tool assembly/use feedback)
