### ISSUE TITLE
hardware dev. of Oil Testing Kit

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#7]
(formerly "dev of targeted sampling kits for community-defined pollutants")

Mathew begins coordinating development of targeted sampling kits based on community-defined pollutant questions.
- [ ] make construction simple enough that we don't need to teach it
- [x] make moddable kits that hold onto power users within our kit ecology
- [ ] improve kit instructions, videos (#24)

Specific hardware to-dos:
- [x] find L-angles and clips
- [x] plan out black ink, then silver ink, printing onto corrugated for "frame"
- [x] develop black-lined baffle possibly separate from frame
- [x] how to print onto the bench? seizure palace (? @mathewlippincott) or just a same-sized card glued on top?
- [x] finish white (or silver-printed, from same sheet as frame) calibration wedge and test it out - and don't make sample hole too deep or this won't work

**Comment by mathewlippincott** [comment]
I'll summarize a bit from the open water call today.. that's a good starting point, + tarball prize

**Comment by jywarren** [comment]
Cool - TP, which is now #17, although we'll be planning some of that offline.

**Comment by jywarren** [comment]
@mathewlippincott - updated this based on our handwritten notes

**Comment by jywarren** [comment]
also follow developments posted here: http://publiclab.org/notes/mathew/08-01-2014/hardware-design-work-for-the-oil-testing-kit

**Comment by jywarren** [comment]
Tracking these all here now: https://github.com/publiclab/spectrometer3/issues
