### ISSUE TITLE
create a research blog

### ISSUE THREAD

**Issue by jywarren** [publiclab/homebrew-sensing#9]
create a research blog in spectrometry techniques (nom. Mathew, maybe Jeff?)

**Comment by jywarren** [comment]
We should coordinate this with the lead-in and constant updates for the KS.

**Comment by jywarren** [comment]
Is this coherent enough, @steviepubliclab? http://publiclab.org/blog/oil-testing-kit 

We could promote it on SpectralWorkbench.org, if so, or do you have suggestions?

**Comment by steviepubliclab** [comment]
woah is this all the research notes taged OTK?

**Comment by jywarren** [comment]
haha yes

**Comment by steviepubliclab** [comment]
Might be misleading that it's listed blog, and the top links into the story
blog page. Maybe title it something else? But it's really neat! I like it a
lot! Nice to read through the flow, looks great.

**Comment by jywarren** [comment]
OK, gotta advertise this somewhere now.
